More convenient redirect to stderr

diff --git a/create_script b/create_script
--- a/create_script
+++ b/create_script
@@ -9,13 +9,13 @@
 main()
 {
     if [[ $# -ne 1 ]]; then
-        echo "Missing script argument." 1>&2
-        echo "Usage: create_script <script>" 1>&2
+        echo "Missing script argument." >&2
+        echo "Usage: create_script <script>" >&2
         exit 1
     fi
     scriptname="$1"
     if script_already_exists; then
-        echo "$scriptname is an existing command, pick another." 1>&2
+        echo "$scriptname is an existing command, pick another." >&2
         exit 1
     fi
     bindir="$HOME/bin"
@@ -43,7 +43,7 @@ verify_bindir()
     if [[ ! -d $bindir ]]; then
         echo "Creating $bindir"
         if ! mkdir "$bindir"; then
-            echo "Failed to create $bindir" 1>&2
+            echo "Failed to create $bindir" >&2
             exit 1
         fi
     fi
diff --git a/edit_script b/edit_script
--- a/edit_script
+++ b/edit_script
@@ -9,17 +9,17 @@
 main()
 {
     if [[ $# -ne 1 ]]; then
-        echo "Missing search term." 1>&2
+        echo "Missing search term." >&2
         exit 1
     fi
     searchterm="$1"
     if ! set_text_editor; then
-        echo "No text editor is defined: set EDITOR or install vim." 1>&2
+        echo "No text editor is defined: set EDITOR or install vim." >&2
         exit 1
     fi 
     edit_candidates=$(search_for_candidates)
     if [[ ! $edit_candidates ]]; then
-        echo "No files match '$searchterm'." 1>&2
+        echo "No files match '$searchterm'." >&2
         exit 1
     fi
     num_of_candidates=$(count_candidates)
