Silence 'type' commands and redirecting error messages to standard error stream.

diff --git a/edit_script b/edit_script
--- a/edit_script
+++ b/edit_script
@@ -9,17 +9,17 @@
 function main
 {
     if [[ $# -ne 1 ]]; then
-        echo "Missing search term."
+        echo "Missing search term." 1>&2
         exit 1
     fi
     searchterm="$1"
     if ! set_text_editor; then
-        echo "No text editor is defined: set EDITOR or install vim."
+        echo "No text editor is defined: set EDITOR or install vim." 1>&2
         exit 1
     fi 
     edit_candidates=$(search_for_candidates)
     if [[ ! $edit_candidates ]]; then
-        echo "No files match '$searchterm'."
+        echo "No files match '$searchterm'." 1>&2
         exit 1
     fi
     num_of_candidates=$(count_candidates)
@@ -43,7 +43,7 @@ function search_for_candidates
 function set_text_editor
 {
     if [[ ! $EDITOR ]]; then
-        if type vim; then
+        if type vim &> /dev/null; then
             EDITOR="vim"
         else
             return 1
